### ISSUE TITLE
Is clientHelloMsg13 missing or unimplemented?

### ISSUE THREAD

**Issue by phuslu** [cloudflare/tls-tris#19]
This is a brilliant project! Thank you for your works.

I noticed that serverHelloMsg13 was implemented for building a tls1.3 server.
Seems that clientHelloMsg13 missed and it prevented me to create a tls1.3 client.

If my understanding is right, any thoughts about the `tls1.3 client` ?
Thank you again!

**Comment by phuslu** [comment]
After go through codes(If my undestanding is right), https://github.com/cloudflare/tls-tris/blob/ce8448ab35b7056585e86dfc8c8cb011d9b9f754/13.go#L53 says it's a TODO item.

**Comment by FiloSottile** [comment]
Hello, and thank you!

There is no need for a separate clientHelloMsg13 object, because the Client Hello happens before version negotiation, so it has to be a valid TLS 1.0/1.2/1.3 CH, all at the same time.

The TODO is unrelated and about the Hello Retry Request message.

Note, however, that a lot of other pieces are missing from a client implementation.
